### PR TITLE
Reset for 2016-2017

### PR DESCRIPTION
**Pull request by ariporad**
I think I did this right... @strugee: can you confirm?

### CODE REVIEW

**Comment by ariporad** [comment]
When this gets merged, we need to squash and merge.

**Comment by strugee** [comment]
@ariporad if it's not inconvenient make the tag name `2015-16` for consistency

**Comment by strugee** [comment]
@ariporad this looks okay, but you should **not** squash and merge. Why? Because you're irrevocably destroying historical information about where changes are coming from. When you go to merge in upstream changes a second time, you'll have a very, very bad time.

Generally speaking this is caused by one of the uglier aspects of git's design. I use rebase all the time but strictly speaking (IMHO) it's pretty gross and is a wart on the way VCS should work, and that becomes really obvious in non-trivial scenarios like this one. If this were, say, a very recent version of hg [with the Evolve extension enabled][1], then you wouldn't have this problem. But sadly, we don't. Ergo: don't squash and merge.

(As a side note, I've been meaning to write a blog post for a while on why I hate squash and merge. I'll give you the link when it's online.)

 [1]: https://www.mercurial-scm.org/wiki/ChangesetEvolution

**Comment by adamperlin** [comment]
Sorry I didn't get a chance to comment on this. Thanks for going ahead.

**Pull request merged**
